### ISSUE TITLE
not so smooth

### ISSUE THREAD

**Issue by larroy** [heynemann/r3#2]
After much fiddling around

http://localhost:9999/  returns 404

r3-map --redis-port=6379 --mapper-key=mapper-1 --mapper-class="test.count_words_mapper.CountWordsMapper" hangs and does nothing

r3-app --redis-port=6379 -c app_config.py 
WARNING:root:404 GET / (127.0.0.1) 0.89ms
WARNING:root:404 GET /favicon.ico (127.0.0.1) 0.30ms
WARNING:root:404 GET / (127.0.0.1) 0.46ms
WARNING:root:404 GET /favicon.ico (127.0.0.1) 0.37ms
WARNING:root:404 GET / (127.0.0.1) 0.34ms
WARNING:root:404 GET /favicon.ico (127.0.0.1) 0.41ms
WARNING:root:404 GET / (127.0.0.1) 0.33ms
WARNING:root:404 GET /favicon.ico (127.0.0.1) 0.30ms
WARNING:root:404 GET / (127.0.0.1) 0.31ms
WARNING:root:404 GET /favicon.ico (127.0.0.1) 0.36ms

not obvious that in web/config.py one has to change redis port....

How can I add the cluster nodes?

**Comment by heynemann** [comment]
Sorry Pedro for this. It is a VERY ALPHA release. Sorry for the redis
thing. I'll try to clean it up a little tomorrow. Really sorry.

You have to acess http://localhost:9999/stream/count-words

And you can fire as many mappers as you want to.

Does that help?

Cheers,
Bernardo Heynemann

**Comment by heynemann** [comment]
Did you get it working larroy? Cluster nodes can easily be added using http://supervisord.org/

If you need help setting it up, just let me know.

Cheers,

**Comment by larroy** [comment]
Hi Bernardo

I was just evaluating your product as I currently use disco. I think you
have some nice ideas in r3 but unfortunately there are unsolved issues
which are solved in disco such as propagating the python code and packages
to the nodes.  Also I didn't manage to fully run the example successfully.

Also I didn't like the r3-map command to start a process. I would rather
start a script and have the library manage everything in the background.

But nonetheless congratulations for having some fresh ideas and sharing
them on github.

Pedro.

On Mon, Aug 13, 2012 at 7:47 PM, Bernardo Heynemann <
notifications@github.com> wrote:

> Did you get it working larroy? Cluster nodes can easily be added using
> http://supervisord.org/
> 
> If you need help setting it up, just let me know.
> 
> Cheers,
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/heynemann/r3/issues/2#issuecomment-7699935.

## 

Pedro Larroy Tovar   |    http://pedro.larroy.com/
