### ISSUE TITLE
Big Data readiness?

### ISSUE THREAD

**Issue by andr0s** [heynemann/r3#7]
How will R3 handle really big amount of data? Let's say, 1TB at least (much more than the amount of RAM the node has). From the given examples it's unclear because you readlines() that will kill the server in this situation. But I thought that it might be just an example which can be refactored to handle big amounts of data.

**Comment by heynemann** [comment]
The current version won't work for that amount of data. We could change it to be a stream flowing through the mappers, though.

**Comment by mansilla** [comment]
perhaps instead of

``` python
def process(self, app, arguments):
    with open(abspath(join(dirname(__file__), 'chekhov.txt'))) as f:
         contents = f.readlines()

    return [line.lower() for line in contents]
```

you can simply

``` python
def process(self, app, arguments):
    with open(abspath(join(dirname(__file__), 'chekhov.txt'))) as f:
         line = f.readline()
         while line:
             yield line.lower()
             line = f.readline()
```

xD

**Comment by heynemann** [comment]
I don't think that'll work as well due to our storage of the data to be processed beforehand.

We'd need to change the way it does things.
